export const urls = {
  homePageUrl: '/',
  jsHistoryUrl: '/jshistory',
  counterUrl: '/counter',
  toDoUrl: '/todo',
  hackertyperUrl: '/hackertyper',
  mortgageCalculatorUrl: '/mortgage-calculator',
  memoryGameUrl: '/memory-game',
  jsAdoptionByMicrosoftUrl: 'adoption-by-microsoft',
  jsCreationAtNetscapeUrl: 'creation-at-netscape',
  jsTheRiseOfJScriptUrl: 'the-rise-of-jscript',
  jsGrowthAndStandardizationUrl: 'growth-and-standardization',
  jsReachingMaturityUrl: 'reaching-maturity',
  jsAdoptionByMicrosoftUrlAll: '/jshistory#adoption-by-microsoft',
  jsCreationAtNetscapeUrlAll: '/jshistory#creation-at-netscape',
  jsTheRiseOfJScriptUrlAll: '/jshistory#the-rise-of-jscript',
  jsGrowthAndStandardizationUrlAll: '/jshistory#growth-and-standardization',
  jsReachingMaturityUrlAll: '/jshistory#reaching-maturity',
}
